name: Sync issue labels from docs repository

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

on:
  push:
    branches:
      - saga
    paths:
      - ".github/workflows/sync-issue-labels.yaml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync_issue_labels:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Sync issue labels from docs repository
        run: gh label clone NordicSemiconductor/asset-tracker-cloud-docs --force
