name: Sync issue labels from docs repository

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  issues: write

on:
  push:
    branches:
      - saga
    paths:
      - ".github/workflows/sync-issue-labels.yaml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync_issue_labels:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Sync issue labels from docs repository
        run: gh label clone NordicSemiconductor/asset-tracker-cloud-docs --force
